services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hephaestus-frontend
    ports:
      - "3001:80"
    environment:
      VITE_API_BASE_URL: https://localhost:7168
    depends_on:
      - hephaestus

  hephaestus:
    image: hephaestus
    build:
      context: .
      dockerfile: Hephaestus/Dockerfile
    environment:
      - HeadHunter__AccessToken=${HEADHUNTER_ACCESS_TOKEN}
      - HeadHunter__ClientSecret=${HEADHUNTER_CLIENT_SECRET}
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "7168:8080"
      - "7169:8081"

  postgres:
    image: postgres:18
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"