// <auto-generated />
using System;
using Hephaestus.Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hephaestus.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421070103_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hephaestus.Domain.Entities.KeySkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RawVacancyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RawVacancyId");

                    b.ToTable("KeySkills");
                });

            modelBuilder.Entity("Hephaestus.Domain.Entities.RawVacancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("HeadHunterId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VacancyDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VacancyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RawVacancies");
                });

            modelBuilder.Entity("Hephaestus.Domain.Entities.KeySkill", b =>
                {
                    b.HasOne("Hephaestus.Domain.Entities.RawVacancy", null)
                        .WithMany("KeySkills")
                        .HasForeignKey("RawVacancyId");
                });

            modelBuilder.Entity("Hephaestus.Domain.Entities.RawVacancy", b =>
                {
                    b.Navigation("KeySkills");
                });
#pragma warning restore 612, 618
        }
    }
}
