// <auto-generated />
using System;
using Hephaestus.Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hephaestus.Application.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422181926_AddSkiils")]
    partial class AddSkiils
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hephaestus.Domain.Entities.CleanSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Counter")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("CleanSkills");
                });

            modelBuilder.Entity("Hephaestus.Domain.Entities.KeySkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RawVacancyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RawVacancyId");

                    b.ToTable("KeySkills");
                });

            modelBuilder.Entity("Hephaestus.Domain.Entities.RawVacancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("HeadHunterId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VacancyDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VacancyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HeadHunterId")
                        .IsUnique();

                    b.ToTable("RawVacancies");
                });

            modelBuilder.Entity("Hephaestus.Domain.Entities.SkillOnReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Counter")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SuggestedDisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SkillsOnReview");
                });

            modelBuilder.Entity("Hephaestus.Domain.Entities.SkillRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildSkillId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ParentSkillId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChildSkillId");

                    b.HasIndex("ParentSkillId");

                    b.ToTable("SkillRelations");
                });

            modelBuilder.Entity("Hephaestus.Domain.Entities.SkillSynonym", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CleanSkillId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFromNormalization")
                        .HasColumnType("boolean");

                    b.Property<string>("SynonymName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CleanSkillId");

                    b.ToTable("SkillSynonyms");
                });

            modelBuilder.Entity("Hephaestus.Domain.Entities.KeySkill", b =>
                {
                    b.HasOne("Hephaestus.Domain.Entities.RawVacancy", null)
                        .WithMany("KeySkills")
                        .HasForeignKey("RawVacancyId");
                });

            modelBuilder.Entity("Hephaestus.Domain.Entities.SkillRelation", b =>
                {
                    b.HasOne("Hephaestus.Domain.Entities.CleanSkill", "ChildSkill")
                        .WithMany("ChildRelations")
                        .HasForeignKey("ChildSkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hephaestus.Domain.Entities.CleanSkill", "ParentSkill")
                        .WithMany("ParentRelations")
                        .HasForeignKey("ParentSkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildSkill");

                    b.Navigation("ParentSkill");
                });

            modelBuilder.Entity("Hephaestus.Domain.Entities.SkillSynonym", b =>
                {
                    b.HasOne("Hephaestus.Domain.Entities.CleanSkill", "CleanSkill")
                        .WithMany("Synonyms")
                        .HasForeignKey("CleanSkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CleanSkill");
                });

            modelBuilder.Entity("Hephaestus.Domain.Entities.CleanSkill", b =>
                {
                    b.Navigation("ChildRelations");

                    b.Navigation("ParentRelations");

                    b.Navigation("Synonyms");
                });

            modelBuilder.Entity("Hephaestus.Domain.Entities.RawVacancy", b =>
                {
                    b.Navigation("KeySkills");
                });
#pragma warning restore 612, 618
        }
    }
}
